export const PRODUCTS = [
  {
    id: 1,
    name: "Neff Daily Heather Beanie Hat",
    category: "Hats",
    imageUrl: "https://m.media-amazon.com/images/I/910NTWqIKZL._AC_UX522_.jpg",
    price: 25,
    color: "Maroon Heather",
    stock: 5,

    brand: "NEFF",
    page: "https://neffheadwear.com",
  },

  {
    id: 2,
    name: "Carhartt Men's Odessa Ball Cap",
    category: "Hats",
    imageUrl: "https://m.media-amazon.com/images/I/61x8RDB3NML._AC_UX569_.jpg",
    price: 18,
    stock: 5,
    color: "Black",
    brand: "Carhartt",
    page: "https://www.carhartt.com/mens-Hats",
  },

  {
    id: 3,
    name: "adidas Relaxed Fit Strapback Cap",
    category: "Hats",
    stock: 5,
    imageUrl: "https://m.media-amazon.com/images/I/7105gGsM6QL._AC_UX569_.jpg",
    price: 35,
    color: "Black/White",
    brand: "adidas",
    page: "https://www.adidas.com/us/originals-mens-metal-logo-2-relaxed-fit-strapback-cap/BQ099.html",
  },

  {
    id: 4,
    name: "Volcom Deadly Stones Snow Beanie",
    category: "Hats",
    imageUrl: "https://m.media-amazon.com/images/I/91cv4sPSfUL._AC_UX466_.jpg",
    price: 25,
    stock: 5,
    color: "Black",
    brand: "Volcom",
    page: "https://www.volcom.com/mens-snow-beanie",
  },

  {
    id: 5,
    name: "U.S. Polo Assn Baseball Hat",
    category: "Hats",
    imageUrl: "https://m.media-amazon.com/images/I/71-ar+n69gS._AC_UX569_.jpg",
    stock: 5,
    price: 18,
    chosen: true,
    color: "White",
    brand: "US Polo",
    page: "https://www.uspoloshoes.com/mens-Hats",
  },

  {
    id: 6,
    name: "BOSS Logo Twill Cap",
    category: "Hats",
    imageUrl: "https://m.media-amazon.com/images/I/71vz-XjGeeL._AC_UX679_.jpg",
    stock: 5,
    price: 14,
    color: "White",
    brand: "BOSS",
    page: "https://www.boss.com/us/mens-Hats",
  },

  {
    id: 7,
    name: "Lacoste Big Croc Hat",
    category: "Hats",
    imageUrl: "https://m.media-amazon.com/images/I/81DuVoPM45L._AC_UX679_.jpg",
    stock: 5,
    price: 18,
    chosen: true,
    color: "White",
    brand: "Lacoste",
    page: "https://www.lacoste.com/us/mens-Hats",
  },

  {
    id: 8,
    name: "Champion Men's Beanie",
    category: "Hats",
    imageUrl: "https://m.media-amazon.com/images/I/61aHo0ci15S._AC_UX569_.jpg",
    stock: 5,
    price: 14,
    color: "Black/White",
    brand: "Champion",
    page: "https://www.championHats.com/mens-Hats",
  },

  {
    id: 9,
    name: "Volcom Men's Full Stone",
    category: "Hats",
    imageUrl: "https://m.media-amazon.com/images/I/71dDvoBNWiL._AC_UX569_.jpg",
    stock: 5,
    price: 35,
    color: "Black",
    brand: "Volcom",
    page: "https://www.volcom.com/us/mens-Hats",
  },

  {
    id: 10,
    category: "Jackets",
    name: "Legendary Whitetails Concealed Carry Softshell",
    imageUrl: "https://m.media-amazon.com/images/I/815pKPX+DZL._AC_UX569_.jpg",
    price: 110,
    stock: 5,
    color: "Black Mossy Oak Overwatch",
    brand: "Legendary Whitetails",
    page: "https://www.legendarywhitetails.com/",
  },

  {
    id: 11,
    name: "Legendary Whitetails Battle The Storm",
    category: "Jackets",
    stock: 5,
    imageUrl: "https://m.media-amazon.com/images/I/71B8WiznpES._AC_UX522_.jpg",
    price: 90,
    color: "State Blue",
    brand: "Legendary Whitetails",
    page: "https://www.legendarywhitetails.com/",
    sizes: {
      tiny: "S",
      smallest: "M",
      small: "L",
      medium: "XL",
      big: "XXL",
      huge: "XXXL",
    },
  },

  {
    id: 12,
    name: "Legendary Whitetails Archer Shirt Thermal",
    category: "Jackets",
    chosen: true,
    imageUrl: "https://m.media-amazon.com/images/I/81fnu5tSOsL._AC_UX569_.jpg",
    price: 90,
    stock: 5,
    color: "Sky",
    brand: "Legendary Whitetails",
    page: "https://www.legendarywhitetails.com/",
    sizes: {
      tiny: "S",
      smallest: "M",
      small: "L",
      medium: "XL",
      big: "XXL",
      huge: "XXXL",
    },
  },

  {
    id: 13,
    name: "Legendary Whitetails Big Woods Fleece",
    category: "Jackets",
    stock: 5,
    imageUrl: "https://m.media-amazon.com/images/I/91Kn1uQWhZL._AC_UX522_.jpg",
    price: 165,
    color: "Burnt Orange",
    chosen: true,
    brand: "Legendary Whitetails",
    page: "https://www.legendarywhitetails.com/",
    sizes: {
      tiny: "S",
      smallest: "M",
      small: "L",
      medium: "XL",
      big: "XXL",
      huge: "XXXL",
    },
  },

  {
    id: 14,
    name: "Legendary Whitetails Full Guard Concealed",
    category: "Jackets",
    imageUrl: "https://m.media-amazon.com/images/I/915xI1d0bhL._AC_UX569_.jpg",
    price: 185,
    stock: 5,
    color: "Charcoal Heather",
    brand: "Legendary Whitetails",
    page: "https://www.legendarywhitetails.com/",
    sizes: {
      tiny: "S",
      smallest: "M",
      small: "L",
      medium: "XL",
      big: "XXL",
      huge: "XXXL",
    },
  },

  {
    id: 20,
    name: "Under Armour Qualifier Storm",
    category: "Womens",
    imageUrl: "https://m.media-amazon.com/images/I/71Yc-2LgwCL._AC_UY550_.jpg",
    stock: 5,
    price: 45,
    color: "Rift Blue",
    brand: "Under Armour",
    page: "https://www.underarmour.com/en-us/Womens/",
    sizes: {
      tiny: "S",
      smallest: "M",
      small: "L",
      medium: "XL",
      big: "XXL",
      huge: "XXXL",
    },
  },

  {
    id: 21,
    name: "ASICS Women's Accelerate Jacket",
    category: "Womens",
    imageUrl: "https://m.media-amazon.com/images/I/51YfLTZESSL._AC_UX679_.jpg",
    price: 90,
    stock: 15,
    color: "Black",
    brand: "ASICS",
    page: "https://www.asics.com/us/en/",
    sizes: {
      tiny: "S",
      smallest: "M",
      small: "L",
      medium: "XL",
      big: "XXL",
      huge: "XXXL",
    },
  },

  {
    id: 22,
    name: "Cutter & Buck Women's Cb Shoreline Half-Zip",
    category: "Womens",
    imageUrl: "https://m.media-amazon.com/images/I/91QV+6ccRQL._AC_UY550_.jpg",
    price: 110,
    stock: 2,
    color: "Bordeaux Heather",
    brand: "Cutter & Buck",
    page: "https://www.cutterbuck.com/",
    sizes: {
      tiny: "S",
      smallest: "M",
      small: "L",
      medium: "XL",
      big: "XXL",
      huge: "XXXL",
    },
  },

  {
    id: 23,
    name: "Dokotoo Spring Summer Deep V Neck",
    category: "Womens",
    imageUrl: "https://m.media-amazon.com/images/I/61Nrz20I2AL._AC_UY550_.jpg",
    price: 120,
    stock: 6,
    chosen: true,
    color: "0 White",
    brand: "Dokotoo",
    page: "https://www.dokotoo.com/",
    sizes: {
      tiny: "S",
      smallest: "M",
      small: "L",
      medium: "XL",
      big: "XXL",
      huge: "XXXL",
    },
  },

  {
    id: 24,
    name: "Star Vixen Women's Short Sleeve",
    category: "Womens",
    imageUrl: "https://m.media-amazon.com/images/I/81GlQi0r86S._AC_UY550_.jpg",
    price: 55,
    stock: 11,
    chosen: true,
    color: "Black",
    brand: "Star Vixen",
    page: "https://www.starvixen.com/",
    sizes: {
      tiny: "S",
      smallest: "M",
      small: "L",
      medium: "XL",
      big: "XXL",
      huge: "XXXL",
    },
  },

  {
    id: 25,
    name: "Legendary Whitetails Women's Open Spaces Dress",
    category: "Womens",
    imageUrl: "https://m.media-amazon.com/images/I/91Aw1l3JkFL._AC_UY550_.jpg",
    price: 135,
    stock: 12,
    color: "Holly Berry",
    brand: "Legendary Whitetails",
    page: "https://www.legendarywhitetails.com/",
    sizes: {
      tiny: "S",
      smallest: "M",
      small: "L",
      medium: "XL",
      big: "XXL",
      huge: "XXXL",
    },
  },

  {
    id: 30,
    name: "Unionbay Cordova Belted Cargo Short",
    category: "Mens",
    imageUrl: "https://m.media-amazon.com/images/I/71IMT9ouCZL._AC_UY550_.jpg",
    price: 35,
    stock: 4,
    color: "Black",
    brand: "Unionbay",
    page: "https://www.unionbay.com/",
    sizes: {
      tiny: "S",
      smallest: "M",
      small: "L",
      medium: "XL",
      big: "XXL",
      huge: "XXXL",
    },
  },

  {
    id: 31,
    name: "Volcom Men's Threedee Tank Top",
    category: "Mens",
    imageUrl: "https://m.media-amazon.com/images/I/810aRKDCM6L._AC_UY550_.jpg",
    price: 40,
    stock: 3,
    color: "Dark",
    brand: "Volcom",
    page: "https://www.volcom.com/",
    sizes: {
      tiny: "S",
      smallest: "M",
      small: "L",
      medium: "XL",
      big: "XXL",
      huge: "XXXL",
    },
  },

  {
    id: 32,
    name: "Nike NSW Club Hoodie Pullover Graphics",
    category: "Mens",
    imageUrl: "https://m.media-amazon.com/images/I/61I7htfopHL._AC_UX569_.jpg",
    price: 55,
    color: "Black",
    stock: 12,
    brand: "Nike",
    page: "https://www.nike.com/",
    sizes: {
      tiny: "S",
      smallest: "M",
      small: "L",
      medium: "XL",
      big: "XXL",
      huge: "XXXL",
    },
  },

  {
    id: 33,
    name: "Nike Sportswear Club Short",
    category: "Mens",
    imageUrl: "https://m.media-amazon.com/images/I/81A25sdpNRL._AC_UY550_.jpg",
    price: 25,
    stock: 14,
    color: "Dark Gray Heather",
    brand: "Nike",
    page: "https://www.nike.com/",
    sizes: {
      tiny: "S",
      smallest: "M",
      small: "L",
      medium: "XL",
      big: "XXL",
      huge: "XXXL",
    },
  },

  {
    id: 34,
    name: "Volcom Men's Stone Tech Short",
    category: "Mens",
    imageUrl: "https://m.media-amazon.com/images/I/61UIW8yZLWL._AC_UX569_.jpg",
    price: 50,
    stock: 2,
    color: "Black",
    brand: "Volcom",
    page: "https://www.volcom.com/",
    sizes: {
      tiny: "S",
      smallest: "M",
      small: "L",
      medium: "XL",
      big: "XXL",
      huge: "XXXL",
    },
  },

  {
    id: 35,
    name: "Legendary Whitetail Navigator Fleece",
    category: "Jackets",
    imageUrl: "https://m.media-amazon.com/images/I/91R9jz6wRDS._AC_UX522_.jpg",
    price: 130,
    stock: 6,
    color: "Navy",
    brand: "Legendary Whitetails",
    page: "https://www.legendarywhitetails.com/",
    sizes: {
      tiny: "S",
      smallest: "M",
      small: "L",
      medium: "XL",
      big: "XXL",
      huge: "XXXL",
    },
  },

  {
    id: 45,
    name: "Ray-Ban RB3016 Clubmaster",
    category: "Glasses",
    imageUrl: "https://m.media-amazon.com/images/I/51h6P0hthcL._AC_UX679_.jpg",
    price: 130,
    stock: 6,
    color: "Black on Gold/G-15 Green",
    brand: "Ray-Ban",
    page: "https://www.ray-ban.com/",
  },

  {
    id: 46,
    name: "Ray-Ban Rb4165 Justin",
    category: "Glasses",
    imageUrl: "https://m.media-amazon.com/images/I/51QExLzUCBL._AC_UX679_.jpg",
    price: 50,
    stock: 6,
    color: "Rubber Brown",
    brand: "Ray-Ban",
    page: "https://www.ray-ban.com/",
  },

  {
    id: 47,
    name: "Maui Jim Hema",
    category: "Glasses",
    imageUrl: "https://m.media-amazon.com/images/I/51RDoQalqKL._AC_UX679_.jpg",
    price: 120,
    stock: 16,
    color: "Crystal Matte",
    brand: "Maui Jim",
    page: "https://www.mauijim.com/",
  },

  {
    id: 48,
    name: "Glasses Costa Del Mar",
    category: "Glasses",
    imageUrl: "https://m.media-amazon.com/images/I/51C4+CIhKxL._AC_UX679_.jpg",
    price: 70,
    stock: 6,
    color: "Mate Azul",
    brand: "Costa Del Mar",
    page: "https://www.costadelmar.com/",
  },

  {
    id: 49,
    name: "ARNETTE An4202 Fastball ",
    category: "Glasses",
    imageUrl: "https://m.media-amazon.com/images/I/412rirxsY8L._AC_UX679_.jpg",
    price: 150,
    stock: 6,
    color: "Black on Grey",
    brand: "ARNETTE",
    page: "https://www.arnette.com/",
  },

  {
    id: 50,
    name: "Maui Jim Koki Playa",
    category: "Glasses",
    imageUrl: "https://m.media-amazon.com/images/I/513L66iANhL._AC_UX679_.jpg",
    price: 110,
    stock: 6,
    color: "Tortuga Oliva",
    brand: "Maui Jim",
    page: "https://www.mauijim.com/",
  },
];
