const PRODUCTS = [
  {
    id: 1,
    title: "Hats",
    routeName: "hats",
    items: [
      {
        id: 1,
        name: "Neff Daily Heather Beanie Hat for Men and Women",
        imageUrl:
          "https://m.media-amazon.com/images/I/910NTWqIKZL._AC_UX522_.jpg",
        price: 25,
        description: "Carvel trend hats",
        stock: 7,
        color: "Maroon Heather",
        sizes: "One Size",
        brand: "NEFF",
        page: "https://neffheadwear.com",
        info: {
          first: "Adjustable closure",
          second: "Machine Wash",
          third: "Imported",
          fourth:
            "Ultra soft beanie keeps your head feeling comfortable and warm while looking cool",
        },
      },

      {
        id: 2,
        name: "Carhartt Men's 100289 Odessa Ball Cap",
        imageUrl:
          "https://m.media-amazon.com/images/I/61x8RDB3NML._AC_UX569_.jpg",
        price: 18,
        description: "Carvel trend hats",
        stock: 7,
        color: "Black",
        sizes: "One Size",
        brand: "Carhartt",
        page: "https://www.carhartt.com/mens-hats",
        info: {
          first: "Adjustable closure",
          second: "Machine Wash",
          third: "Imported",
          fourth:
            "Ultra soft beanie keeps your head feeling comfortable and warm while looking cool",
        },
      },
      {
        id: 3,
        name: "adidas Originals Men's Metal Logo 2 Relaxed Fit Strapback Cap",
        imageUrl:
          "https://m.media-amazon.com/images/I/7105gGsM6QL._AC_UX569_.jpg",
        price: 35,
        description: "Carvel trend hats",
        stock: 7,
        color: "Black/White",
        sizes: "One Size",
        brand: "adidas",
        page: "https://www.adidas.com/us/originals-mens-metal-logo-2-relaxed-fit-strapback-cap/BQ099.html",
        info: {
          first: "Adjustable closure",
          second: "Machine Wash",
          third: "Imported",
          fourth:
            "Ultra soft beanie keeps your head feeling comfortable and warm while looking cool",
        },
      },
      {
        id: 4,
        name: "Volcom Men's Deadly Stones Snow Beanie",
        imageUrl:
          "https://m.media-amazon.com/images/I/91cv4sPSfUL._AC_UX466_.jpg",
        price: 25,
        description: "Carvel trend hats",
        stock: 7,
        color: "Black",
        sizes: "One Size",
        brand: "Volcom",
        page: "https://www.volcom.com/mens-snow-beanie",
        info: {
          first: "Adjustable closure",
          second: "Machine Wash",
          third: "Imported",
          fourth:
            "Ultra soft beanie keeps your head feeling comfortable and warm while looking cool",
        },
      },
      {
        id: 5,
        name: "U.S. Polo Assn. Mens Mens Washed Twill Cotton Adjustable Baseball Hat with Pony Logo and Curved Brim",
        imageUrl:
          "https://m.media-amazon.com/images/I/71-ar+n69gS._AC_UX569_.jpg",
        price: 18,
        description: "Carvel trend hats",
        stock: 7,
        color: "White",
        sizes: "One Size",
        brand: "US Polo",
        page: "https://www.uspoloshoes.com/mens-hats",
        info: {
          first: "Adjustable closure",
          second: "Machine Wash",
          third: "Imported",
          fourth:
            "Ultra soft beanie keeps your head feeling comfortable and warm while looking cool",
        },
      },
      {
        id: 6,
        name: "BOSS Men's Logo Twill Cap 1",
        imageUrl:
          "https://m.media-amazon.com/images/I/71vz-XjGeeL._AC_UX679_.jpg",
        price: 14,
        description: "Carvel trend hats",
        stock: 5,
        color: "White",
        sizes: "One Size",
        brand: "BOSS",
        page: "https://www.boss.com/us/mens-hats",
        info: {
          first: "Adjustable closure",
          second: "Machine Wash",
          third: "Imported",
          fourth:
            "Ultra soft beanie keeps your head feeling comfortable and warm while looking cool",
        },
      },
      {
        id: 7,
        name: "Lacoste Men's Big Croc Twill Adjustable Leather Strap Hat",
        imageUrl:
          "https://m.media-amazon.com/images/I/81DuVoPM45L._AC_UX679_.jpg",
        price: 18,
        description: "Carvel trend hats",
        stock: 2,
        color: "White",
        sizes: "One Size",
        brand: "Lacoste",
        page: "https://www.lacoste.com/us/mens-hats",
        info: {
          first: "Adjustable closure",
          second: "Machine Wash",
          third: "Imported",
          fourth:
            "Ultra soft beanie keeps your head feeling comfortable and warm while looking cool",
        },
      },
      {
        id: 8,
        name: "Champion Men's Beanie",
        imageUrl:
          "https://m.media-amazon.com/images/I/61aHo0ci15S._AC_UX569_.jpg",
        price: 14,
        description: "Carvel trend hats",
        stock: 12,
        color: "Black/White",
        sizes: "One Size",
        brand: "Champion",
        page: "https://www.championhats.com/mens-hats",
        info: {
          first: "Adjustable closure",
          second: "Machine Wash",
          third: "Imported",
          fourth:
            "Ultra soft beanie keeps your head feeling comfortable and warm while looking cool",
        },
      },
      {
        id: 9,
        name: "Volcom Men's Full Stone Beanie",
        imageUrl:
          "https://m.media-amazon.com/images/I/71dDvoBNWiL._AC_UX569_.jpg",
        price: 35,
        description: "Carvel trend hats",
        stock: 2,
        color: "Black",
        sizes: "One Size",
        brand: "Volcom",
        page: "https://www.volcom.com/us/mens-hats",
        info: {
          first: "Adjustable closure",
          second: "Machine Wash",
          third: "Imported",
          fourth:
            "Ultra soft beanie keeps your head feeling comfortable and warm while looking cool",
        },
      },
    ],
  },
  {
    id: 2,
    title: "Sneakers",
    routeName: "sneakers",
    items: [
      {
        id: 1,
        name: "SeaVees Men's Sixty Six Sneaker",
        imageUrl:
          "https://m.media-amazon.com/images/I/61b+qtnxfES._AC_UX575_.jpg",
        price: 58,
        description: "Carvel fashion snickers",
        stock: 2,
        color: "Black",
        brand: "Seavees",
        page: "https://www.instagram.com/seavees/",
        info: {
          first: "100% Synthetic",
          second: "Lightly cushioned footbed for excellent comfort",
          third: "Durable rubber outsole for added traction",
          fourth: "Synthetic leather upper - vegan materials",
        },
        sizes: {
          tiny: 7,
          smallest: 8,
          small: 9,
          medium: 10,
          big: 11,
          huge: 12,
        },
      },
      {
        id: 2,
        name: "Levi's Mens Miles Perf Casual Contrast Trim Sneaker Shoe",
        imageUrl:
          "https://m.media-amazon.com/images/I/51IJ-SyRHOS._AC_UY575_.jpg",
        price: 60,
        description: "Carvel fashion snickers",
        stock: 4,
        color: "Charcoal/Black",
        page: "https://www.levi.com.ar/",
        brand: "Levi's",
        info: {
          first: "100% Synthetic",
          second: "Lightly cushioned footbed for excellent comfort",
          third: "Durable rubber outsole for added traction",
          fourth: "Synthetic leather upper - vegan materials",
        },
        sizes: {
          tiny: 7,
          smallest: 8,
          small: 9,
          medium: 10,
          big: 11,
          huge: 12,
        },
      },

      // -----------------------------------------------------------
      {
        id: 3,
        name: "Vans Men's Low-top Trainers",
        imageUrl:
          "https://m.media-amazon.com/images/I/61TUONAxcPL._AC_UY500_.jpg",

        price: 125,
        description: "Carvel fashion snickers",
        stock: 5,
        color: "Waxed Denim Black Gum",
        brand: "Vans",
        page: "https://www.vans.com.ar/homevans/",
        info: {
          first: "100% Synthetic",
          second: "Lightly cushioned footbed for excellent comfort",
          third: "Durable rubber outsole for added traction",
          fourth: "Synthetic leather upper - vegan materials",
        },
        sizes: {
          tiny: 7,
          smallest: 8,
          small: 9,
          medium: 10,
          big: 11,
          huge: 12,
        },
      },
      {
        id: 4,
        name: "Volcom Men's Daycation Flip Flop Sandal",
        imageUrl:
          "https://m.media-amazon.com/images/I/81Mlq5BLBeL._AC_UY625_.jpg",
        price: 95,
        description: "Carvel fashion snickers",
        stock: 3,
        color: "Dark Camo",
        brand: "Volcom",
        page: "https://www.volcom.com/us/mens-shoes",
        info: {
          first: "100% Synthetic",
          second: "Lightly cushioned footbed for excellent comfort",
          third: "Durable rubber outsole for added traction",
          fourth: "Synthetic leather upper - vegan materials",
        },
        sizes: {
          tiny: 7,
          smallest: 8,
          small: 9,
          medium: 10,
          big: 11,
          huge: 12,
        },
      },
      {
        id: 5,
        name: "Nike Men's Court Legacy Gymnastics Shoe",
        imageUrl:
          "https://m.media-amazon.com/images/I/61gmAgzk2FL._AC_UX575_.jpg",
        price: 135,
        description: "Carvel fashion snickers",
        stock: 21,
        color: "White/Black",
        brand: "Nike",
        page: "https://www.nike.com.ar/",
        info: {
          first: "100% Synthetic",
          second: "Lightly cushioned footbed for excellent comfort",
          third: "Durable rubber outsole for added traction",
          fourth: "Synthetic leather upper - vegan materials",
        },
        sizes: {
          tiny: 7,
          smallest: 8,
          small: 9,
          medium: 10,
          big: 11,
          huge: 12,
        },
      },
      {
        id: 6,
        name: "adidas Men's Grand Court Tennis Shoes",
        imageUrl:
          "https://m.media-amazon.com/images/I/61FbqzPD8TL._AC_UX575_.jpg",
        price: 160,
        description: "Carvel fashion snickers",
        stock: 2,
        color: "White/Black",
        brand: "Adidas",
        page: "https://www.adidas.com.ar/",
        info: {
          first: "100% Synthetic",
          second: "Lightly cushioned footbed for excellent comfort",
          third: "Durable rubber outsole for added traction",
          fourth: "Synthetic leather upper - vegan materials",
        },
        sizes: {
          tiny: 7,
          smallest: 8,
          small: 9,
          medium: 10,
          big: 11,
          huge: 12,
        },
      },
      {
        id: 7,
        name: "WETIKE Boys Basketball Shoes Non-Slip ",
        imageUrl:
          "https://m.media-amazon.com/images/I/71I1D88emrL._AC_UY575_.jpg",
        price: 250,
        description: "Carvel fashion snickers",
        stock: 2,
        color: "Black/Red Mars",
        brand: "Jordan",
        page: "https://www.jordan.com.ar/",
        info: {
          first: "100% Synthetic",
          second: "Lightly cushioned footbed for excellent comfort",
          third: "Durable rubber outsole for added traction",
          fourth: "Synthetic leather upper - vegan materials",
        },
        sizes: {
          tiny: 7,
          smallest: 8,
          small: 9,
          medium: 10,
          big: 11,
          huge: 12,
        },
      },
      {
        id: 8,
        name: "Converse High Top Sneaker",
        imageUrl:
          "https://m.media-amazon.com/images/I/618J8qS+RQL._AC_UX575_.jpg",
        price: 210,
        description: "Carvel fashion snickers",
        stock: 11,
        color: "Black",
        brand: "Converse",
        page: "https://www.converse.com.ar/",
        info: {
          first: "100% Synthetic",
          second: "Lightly cushioned footbed for excellent comfort",
          third: "Durable rubber outsole for added traction",
          fourth: "Synthetic leather upper - vegan materials",
        },
        sizes: {
          tiny: 7,
          smallest: 8,
          small: 9,
          medium: 10,
          big: 11,
          huge: 12,
        },
      },
    ],
  },
  {
    id: 3,
    title: "Jackets",
    routeName: "jackets",
    items: [
      {
        id: 1,
        name: "Legendary Whitetails Men's Concealed Carry Softshell Jacket",
        imageUrl:
          "https://m.media-amazon.com/images/I/815pKPX+DZL._AC_UX569_.jpg",
        price: 110,
        description: "Carvel fashion jackets",
        stock: 2,
        color: "Black Mossy Oak Overwatch",
        brand: "Legendary Whitetails",
        page: "https://www.legendarywhitetails.com/",
        info: {
          first: "100% Polyester",
          second: "Machine Wash",
          third: "Zipper closure",
          fourth: "Imported",
        },
        sizes: {
          tiny: "S",
          smallest: "M",
          small: "L",
          medium: "XL",
          big: "XXL",
          huge: "XXXL",
        },
      },
      {
        id: 2,
        name: "Legendary Whitetails Men's Battle The Storm Jacket",
        imageUrl:
          "https://m.media-amazon.com/images/I/71B8WiznpES._AC_UX522_.jpg",
        price: 90,
        description: "Carvel fashion jackets",
        stock: 2,
        color: "State Blue",
        brand: "Legendary Whitetails",
        page: "https://www.legendarywhitetails.com/",
        info: {
          first: "100% Polyester",
          second: "Machine Wash",
          third: "Zipper closure",
          fourth: "Imported",
        },
        sizes: {
          tiny: "S",
          smallest: "M",
          small: "L",
          medium: "XL",
          big: "XXL",
          huge: "XXXL",
        },
      },
      {
        id: 3,
        name: "Legendary Whitetails Men's Archer Shirt Thermal Jacket Lined Coat",
        imageUrl:
          "https://m.media-amazon.com/images/I/81fnu5tSOsL._AC_UX569_.jpg",
        price: 90,
        description: "Carvel fashion jackets",
        stock: 5,
        color: "Sky",
        brand: "Legendary Whitetails",
        page: "https://www.legendarywhitetails.com/",
        info: {
          first: "100% Polyester",
          second: "Machine Wash",
          third: "Zipper closure",
          fourth: "Imported",
        },
        sizes: {
          tiny: "S",
          smallest: "M",
          small: "L",
          medium: "XL",
          big: "XXL",
          huge: "XXXL",
        },
      },
      {
        id: 4,
        name: "Legendary Whitetails Men's Big Woods Fleece Shirt Jacket",
        imageUrl:
          "https://m.media-amazon.com/images/I/91Kn1uQWhZL._AC_UX522_.jpg",
        price: 165,
        description: "Carvel fashion jackets",
        stock: 10,
        color: "Burnt Orange",
        brand: "Legendary Whitetails",
        page: "https://www.legendarywhitetails.com/",
        info: {
          first: "100% Polyester",
          second: "Machine Wash",
          third: "Zipper closure",
          fourth: "Imported",
        },
        sizes: {
          tiny: "S",
          smallest: "M",
          small: "L",
          medium: "XL",
          big: "XXL",
          huge: "XXXL",
        },
      },
      {
        id: 5,
        name: "Legendary Whitetails Men's Full Guard Concealed Carry Utility Sweatshirt",
        imageUrl:
          "https://m.media-amazon.com/images/I/915xI1d0bhL._AC_UX569_.jpg",
        price: 185,
        description: "Carvel fashion jackets",
        stock: 2,
        color: "Charcoal Heather",
        brand: "Legendary Whitetails",
        page: "https://www.legendarywhitetails.com/",
        info: {
          first: "100% Polyester",
          second: "Machine Wash",
          third: "Zipper closure",
          fourth: "Imported",
        },
        sizes: {
          tiny: "S",
          smallest: "M",
          small: "L",
          medium: "XL",
          big: "XXL",
          huge: "XXXL",
        },
      },
    ],
  },
  {
    id: 4,
    title: "Womens",
    routeName: "womens",
    items: [
      {
        id: 1,
        name: "Under Armour Women's Qualifier Storm Packable Jacket",
        imageUrl:
          "https://m.media-amazon.com/images/I/71Yc-2LgwCL._AC_UY550_.jpg",
        price: 45,
        stock: 12,
        color: "Rift Blue",
        brand: "Under Armour",
        page: "https://www.underarmour.com/en-us/womens/",
        info: {
          first: "95% Polyester. 5% Spandex",
          second: "Machine Wash",
          third: "Pull on closure",
          fourth: "Imported",
        },
        sizes: {
          tiny: "S",
          smallest: "M",
          small: "L",
          medium: "XL",
          big: "XXL",
          huge: "XXXL",
        },
      },
      {
        id: 2,
        name: "ASICS Women's Accelerate Jacket",
        imageUrl:
          "https://m.media-amazon.com/images/I/51YfLTZESSL._AC_UX679_.jpg",
        price: 90,
        stock: 22,
        color: "Black",
        brand: "ASICS",
        page: "https://www.asics.com/us/en/",
        info: {
          first: "95% Polyester. 5% Spandex",
          second: "Machine Wash",
          third: "Pull on closure",
          fourth: "Imported",
        },
        sizes: {
          tiny: "S",
          smallest: "M",
          small: "L",
          medium: "XL",
          big: "XXL",
          huge: "XXXL",
        },
      },
      {
        id: 3,
        name: "Cutter & Buck Women's Cb Shoreline Half-Zip",
        imageUrl:
          "https://m.media-amazon.com/images/I/91QV+6ccRQL._AC_UY550_.jpg",
        price: 110,
        stock: 2,
        color: "Bordeaux Heather",
        brand: "Cutter & Buck",
        page: "https://www.cutterbuck.com/",
        info: {
          first: "95% Polyester. 5% Spandex",
          second: "Machine Wash",
          third: "Pull on closure",
          fourth: "Imported",
        },
        sizes: {
          tiny: "S",
          smallest: "M",
          small: "L",
          medium: "XL",
          big: "XXL",
          huge: "XXXL",
        },
      },
      {
        id: 4,
        name: "Dokotoo Womens Spring Summer Deep V Neck Ruffle Long Sleeve Floral Print Mini Dress",
        imageUrl:
          "https://m.media-amazon.com/images/I/61Nrz20I2AL._AC_UY550_.jpg",
        price: 120,
        stock: 8,
        color: "0 White",
        brand: "Dokotoo",
        page: "https://www.dokotoo.com/",
        info: {
          first: "95% Polyester. 5% Spandex",
          second: "Machine Wash",
          third: "Pull on closure",
          fourth: "Imported",
        },
        sizes: {
          tiny: "S",
          smallest: "M",
          small: "L",
          medium: "XL",
          big: "XXL",
          huge: "XXXL",
        },
      },
      {
        id: 5,
        name: "Star Vixen Women's Short Sleeve Twist-Front Printed Maxi Dress",
        imageUrl:
          "https://m.media-amazon.com/images/I/81GlQi0r86S._AC_UY550_.jpg",
        price: 45,
        stock: 2,
        color: "Black",
        brand: "Star Vixen",
        page: "https://www.starvixen.com/",
        info: {
          first: "95% Polyester. 5% Spandex",
          second: "Machine Wash",
          third: "Pull on closure",
          fourth: "Imported",
        },
        sizes: {
          tiny: "S",
          smallest: "M",
          small: "L",
          medium: "XL",
          big: "XXL",
          huge: "XXXL",
        },
      },
      {
        id: 6,
        name: "Legendary Whitetails Women's Open Spaces Dress",
        imageUrl:
          "https://m.media-amazon.com/images/I/91Aw1l3JkFL._AC_UY550_.jpg",
        price: 135,
        stock: 5,
        color: "Holly Berry",
        brand: "Legendary Whitetails",
        page: "https://www.legendarywhitetails.com/",
        info: {
          first: "95% Polyester. 5% Spandex",
          second: "Machine Wash",
          third: "Pull on closure",
          fourth: "Imported",
        },
        sizes: {
          tiny: "S",
          smallest: "M",
          small: "L",
          medium: "XL",
          big: "XXL",
          huge: "XXXL",
        },
      },
      {
        id: 7,
        name: "Star Vixen Women's Cutout Cold Shoulder Short Sleeve Faux Wrap Dress",
        imageUrl:
          "https://m.media-amazon.com/images/I/617LQEMZK9L._AC_UY550_.jpg",
        price: 20,
        stock: 4,
        color: "Black",
        brand: "Star Vixen",
        page: "https://www.starvixen.com/",
        info: {
          first: "95% Polyester. 5% Spandex",
          second: "Machine Wash",
          third: "Pull on closure",
          fourth: "Imported",
        },
        sizes: {
          tiny: "S",
          smallest: "M",
          small: "L",
          medium: "XL",
          big: "XXL",
          huge: "XXXL",
        },
      },
    ],
  },
  {
    id: 5,
    title: "Mens",
    routeName: "mens",
    items: [
      {
        id: 1,
        name: "Unionbay Men's Cordova Belted Messenger Cargo Short",
        imageUrl:
          "https://m.media-amazon.com/images/I/71IMT9ouCZL._AC_UY550_.jpg",
        price: 35,
        stock: 2,
        color: "Black",
        brand: "Unionbay",
        page: "https://www.unionbay.com/",
        info: {
          first: "100% Polyester",
          second: "Machine Wash",
          third: "Zipper closure",
          fourth: "Imported",
        },
        sizes: {
          tiny: "S",
          smallest: "M",
          small: "L",
          medium: "XL",
          big: "XXL",
          huge: "XXXL",
        },
      },
      {
        id: 2,
        name: "Volcom Men's Threedee Tank Top",
        imageUrl:
          "https://m.media-amazon.com/images/I/810aRKDCM6L._AC_UY550_.jpg",
        price: 40,
        stock: 2,
        color: "Dark",
        brand: "Volcom",
        page: "https://www.volcom.com/",
        info: {
          first: "100% Polyester",
          second: "Machine Wash",
          third: "Zipper closure",
          fourth: "Imported",
        },
        sizes: {
          tiny: "S",
          smallest: "M",
          small: "L",
          medium: "XL",
          big: "XXL",
          huge: "XXXL",
        },
      },
      {
        id: 3,
        name: "Nike NSW Club Hoodie Pullover Graphics",
        imageUrl:
          "https://m.media-amazon.com/images/I/61I7htfopHL._AC_UX569_.jpg",
        price: 55,
        stock: 2,
        color: "Black",
        brand: "Nike",
        page: "https://www.nike.com/",
        info: {
          first: "100% Polyester",
          second: "Machine Wash",
          third: "Zipper closure",
          fourth: "Imported",
        },
        sizes: {
          tiny: "S",
          smallest: "M",
          small: "L",
          medium: "XL",
          big: "XXL",
          huge: "XXXL",
        },
      },
      {
        id: 4,
        name: "Nike Men's Sportswear Club Short Basketball Graphic",
        imageUrl:
          "https://m.media-amazon.com/images/I/81A25sdpNRL._AC_UY550_.jpg",
        price: 25,
        stock: 2,
        color: "Dark Gray Heather",
        brand: "Nike",
        page: "https://www.nike.com/",
        info: {
          first: "100% Polyester",
          second: "Machine Wash",
          third: "Zipper closure",
          fourth: "Imported",
        },
        sizes: {
          tiny: "S",
          smallest: "M",
          small: "L",
          medium: "XL",
          big: "XXL",
          huge: "XXXL",
        },
      },
      {
        id: 5,
        name: "Volcom Men's Stone Tech Short Sleeve T-Shirt",
        imageUrl:
          "https://m.media-amazon.com/images/I/61UIW8yZLWL._AC_UX569_.jpg",
        price: 50,
        stock: 3,
        color: "Black",
        brand: "Volcom",
        page: "https://www.volcom.com/",
        info: {
          first: "100% Polyester",
          second: "Machine Wash",
          third: "Zipper closure",
          fourth: "Imported",
        },
        sizes: {
          tiny: "S",
          smallest: "M",
          small: "L",
          medium: "XL",
          big: "XXL",
          huge: "XXXL",
        },
      },
      {
        id: 6,
        name: "Legendary Whitetails Men's Navigator Fleece Button Up Shirt",
        imageUrl:
          "https://m.media-amazon.com/images/I/91R9jz6wRDS._AC_UX522_.jpg",
        price: 130,
        stock: 13,
        color: "Navy",
        brand: "Legendary Whitetails",
        page: "https://www.legendarywhitetails.com/",
        info: {
          first: "100% Polyester",
          second: "Machine Wash",
          third: "Zipper closure",
          fourth: "Imported",
        },
        sizes: {
          tiny: "S",
          smallest: "M",
          small: "L",
          medium: "XL",
          big: "XXL",
          huge: "XXXL",
        },
      },
    ],
  },
];

export default PRODUCTS;
